### ISSUE TITLE
Keystore?

### ISSUE THREAD

**Issue by topws** [D-Technologies/EthereumKit#128]
how to create keystore file?

**Comment by yuzushioh** [comment]
Hi @topws EthereumKit does not support keystore file right now. will support it but not sure when

**Comment by HenryGaoGH** [comment]
Hopefully, a Keystore file can be generated as soon as possible

**Comment by quzg** [comment]
is the EthereumKit support “from the privateKey to keystore” ？

**Comment by yuzushioh** [comment]
It does not support a keystore yet.

**Comment by quzg** [comment]
thankyou very much,It does not support a keystore yet.
but,do it support "privateKey to mnemonic"?thank you😃

**Comment by yuzushioh** [comment]
Yes it does support private key and mnemonic.

**Comment by quzg** [comment]
I mean if I have a private key , can I export the corresponding mnemonic use the EthereumKit ? thank u

**Comment by quzg** [comment]
Yes, u are right, thank you so much！ and I have the last question，do you know the how to export the keystore with web3swift or BIP39 or other Foundations ？
