### ISSUE TITLE
Possible issue with "compressed: true"

### ISSUE THREAD

**Issue by sche** [D-Technologies/EthereumKit#135]
https://github.com/D-Technologies/EthereumKit/blob/58bb34623a9d0cdd14eebe9f58a559956900f166/EthereumKit/Key/HDPublicKey.swift#L12

Hi, I am not sure if it is correct that "compressed: true" is used in this place. Could it be a potential issue, or should it be like that?

**Comment by yuzushioh** [comment]
Looks like its okay here. I added some tests on HDPublicKey extended() method #136 . You have to use compressed public key for creating extended public key. It is defined in BIP32.

**Comment by sche** [comment]
Good, thanks. Would be also good to include link to some test vectors used in your unit tests.
I haven't found your generated keys from #136 PR in BIP32 spec test vectors. (https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)

**Comment by yuzushioh** [comment]
@sche Yes you are right. I added extra BIP32 key derivation tests based on vectors in BIP32 spec. #137
