### ISSUE TITLE
Unit in erc20 methods

### ISSUE THREAD

**Issue by FinLaas** [D-Technologies/EthereumKit#139]
Hi, would you please tell me, what's the amount unit used in 
"generateDataParameter(toAddress: String, amount: String) throws -> Data"
method? 
Ether? or GWei?

Thanks.

**Comment by yuzushioh** [comment]
Hi @FinLaas, ERC20 tokens does not have a default unit like Ethereum does. They have something like OMG or KIN. so if you want to send 10 OMG tokens, simply put 10.

**Comment by FinLaas** [comment]
I see. Thanks.
