### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2.1 

### ISSUE THREAD

**Issue by OleksiiShulzhenko** [D-Technologies/EthereumKit#155]
What can I do with this error?
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2.1

**Comment by yuzushioh** [comment]
`carthage update --platform ios --no-use-binaries` should fix that problem.

**Comment by OleksiiShulzhenko** [comment]
@yuzushioh , It did not help. I already did it.
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2.1 compiler: Carthage/Checkouts/CryptoEthereumSwift/Carthage/Build/iOS/CryptoEthereumSwift.framework/Modules/CryptoEthereumSwift.swiftmodule/arm64.swiftmodule

**Comment by yuzushioh** [comment]
could you delete a cache of carthage builds by running `rm -rf ~/Library/Caches/org.carthage.CarthageKit` and try to install EthereumKit again?
