### ISSUE TITLE
Xcode 10.2 compiler freezes on SentTransaction.swift

### ISSUE THREAD

**Issue by DmitryBespalov** [D-Technologies/EthereumKit#162]
When I update the project and rebuild the carthage frameworks, and then build the project for release scheme (Cmd+Shift+I), then the compilation freezes on the SentTransaction.swift file and the build doesn't go anywhere.

Currently, I have no idea why this happens.

**Comment by OleksiiShulzhenko** [comment]
Same.

**Comment by OleksiiShulzhenko** [comment]
carthage bootstrap --platform ios --verbose --new-resolver --no-use-binaries
Wait about an hour.
or  for swift 4.2
TOOLCHAINS=com.apple.dt.toolchain.Swift_4_2 carthage bootstrap --platform ios --verbose --new-resolver --no-use-binaries

**Comment by DmitryBespalov** [comment]
@OleksiiShulzhenko so did it actually build for you?

**Comment by OleksiiShulzhenko** [comment]
@DmitryBespalov Yes.

**Comment by DmitryBespalov** [comment]
ok, for me it took 45 minutes to compile.
