### ISSUE TITLE
Run issus Symbol not found

### ISSUE THREAD

**Issue by imfaker** [D-Technologies/EthereumKit#171]
dyld: Symbol not found: _$s11CryptoSwift4SHA3C7VariantO9keccak256yA2EmFWC
  Referenced from: /private/var/containers/Bundle/Application/2C4323CD-8896-4879-89D7-FF2FB4AA39AD/xxxx.app/Frameworks/CryptoEthereumSwift.framework/CryptoEthereumSwift
  Expected in: /private/var/containers/Bundle/Application/2C4323CD-8896-4879-89D7-FF2FB4AA39AD/xxxx.app/Frameworks/CryptoSwift.framework/CryptoSwift
 in /private/var/containers/Bundle/Application/2C4323CD-8896-4879-89D7-FF2FB4AA39AD/xxxx.app/Frameworks/CryptoEthereumSwift.framework/CryptoEthereumSwift\

In swift 5.1. Xcode 11.3.1.   
Compile Success Error appear after run start.

**Comment by OleksiiShulzhenko** [comment]
@imfaker 
Did you solve this problem?
